OTS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from online_test import views
urlpatterns = [
    path("ots/",include("online_test.urls")),
    path("admin/", admin.site.urls),
    path("",views.welcome,name='welcome'),
]

online_test/urls.py
from django.urls import path
from online_test import views
app_name='user'
urlpatterns = [
    path("welcome",views.welcome,name='welcome'),
    path("signup",views.signup,name='signup'),
    path("store_user",views.store_user,name='store_user'),
    path("login",views.login,name='login'),
    path("homepage",views.homepage,name='homepage'),
    path("subject1",views.subject1,name='subject1'),
    path("subject2",views.subject2,name='subject2'),
    path("subject3",views.subject3,name='subject3'),
    path("result1",views.result1,name='result1'),
    path("result2",views.result2,name='result2'),
    path("result3",views.result3,name='result3'),
    path("profile",views.profile,name='profile'),
    path("profile_save",views.profile_save,name='profile_save'),
    path("test_history",views.test_history,name='test_history'),
    path("logout",views.logout,name='logout'),
    path("aboutUs",views.aboutUs,name='aboutUs'),
]

online_test/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username=models.CharField(primary_key=True,max_length=30)
    password=models.CharField(max_length=10,null=False)
    name=models.CharField(max_length=30,null=False)
    def __str__(self):
        return self.name
    
class Profile(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,primary_key=True)
    fathers_name=models.CharField(max_length=30,default='')
    mothers_name=models.CharField(max_length=30,default='')
    phone=models.CharField(max_length=10,default='')
    email=models.CharField(max_length=30,default='')
    address=models.CharField(max_length=50,default='')
    def __str__(self):
        return self.fathers_name
    
class Test_history(models.Model):
    test_id=models.BigAutoField(auto_created=True,primary_key=True)
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    subject=models.CharField(max_length=25,default='')
    total=models.IntegerField()
    correct=models.IntegerField()
    wrong=models.IntegerField()
    percentage=models.IntegerField()

class Test_paper_subject1(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Test_paper_subject2(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Test_paper_subject3(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
    

online_test/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from online_test.models import *
from django.views.decorators.csrf import csrf_exempt #include this 
import random
def welcome(request):
    template=loader.get_template("welcome.html")
    res=template.render()
    return HttpResponse(res)

def signup(request):
    template=loader.get_template("signup.html")
    res=template.render()
    return HttpResponse(res)

@csrf_exempt # include  this
def store_user(request):
    if request.method=='POST':
        username=request.POST['username']
        if(len(User.objects.filter(username=username))):
            msg='username already taken ....try another username'
            context={
                'msg':msg
            }
            template=loader.get_template("signup.html")
            res=template.render(context,request)
            return HttpResponse(res)
        else:
            user=User() # insertion
            user.username=username
            user.password=request.POST['password']
            user.name=request.POST['name']
            user.save()
            template=loader.get_template("login.html")
            res=template.render()
            return HttpResponse(res)
    else:
        msg='invalid request......first signup'
        context={
            'msg':msg
        }
        template=loader.get_template("signup.html")
        res=template.render(context,request)
        return HttpResponse(res)
    
@csrf_exempt # include  this
def login(request): #authentication
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        if(len(User.objects.filter(username=username))):
            user=User.objects.filter(username=username)
            if(len(user.filter(password=password))):
                request.session['username']=username # login success then ...
                user_data=User.objects.filter(username=username)
                profile_data=Profile.objects.filter(username=username)
                context={
                    'user_data':user_data,
                    'profile_data':profile_data
                }
                template=loader.get_template("homepage.html")
                res=template.render(context,request)
                return HttpResponse(res)
            else:
                msg='incorrect password.......login again'
                context={
                    'msg':msg
                }
                template=loader.get_template("login.html")
                res=template.render(context,request)
                return HttpResponse(res)
        else:
            msg='incorrect username........login again'
            context={
                'msg':msg
            }
            template=loader.get_template("login.html")
            res=template.render(context,request)
            return HttpResponse(res)
    else:
        template=loader.get_template("login.html")
        res=template.render()
        return HttpResponse(res)

def homepage(request):
    if 'username' not in request.session.keys(): 
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    else:
        username=request.session['username']
        user_data=User.objects.filter(username=username)
        profile_data=Profile.objects.filter(username=username)
        context={   
            'user_data':user_data,
            'profile_data':profile_data
        }
        template=loader.get_template("homepage.html")
        res=template.render(context,request)
        return HttpResponse(res)

def profile(request):
    template=loader.get_template("profile.html")
    res=template.render()
    return HttpResponse(res)

@csrf_exempt # include  this
def profile_save(request):
    if request.method=='POST':
        username=request.session.get('username')
        if(len(User.objects.filter(username=username))):
            profile=Profile() #insertion
            profile.username=User.objects.get(username=username)
            profile.fathers_name=request.POST['father_name']
            profile.mothers_name=request.POST['mother_name']
            profile.phone=request.POST['phone']
            profile.email=request.POST['email']
            profile.address=request.POST['address']
            profile.save()
            user_data=User.objects.filter(username=username)
            profile_data=Profile.objects.filter(username=username)
            context={
                'user_data':user_data,
                'profile_data':profile_data
            }
            template=loader.get_template("homepage.html")
            res=template.render(context,request)
            return HttpResponse(res)
        else:
            msg='incorrect username ,profile not updated'
            context={
                'msg':msg
            }
            template=loader.get_template("profile.html")
            res=template.render(context,request)
            return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)

def subject1(request):
    ques=Test_paper_subject1.objects.all()
    quse_list=list(ques)
    random.shuffle(quse_list)
    quse_list=quse_list[:4:1] ###### total questions can be customized
    context={
        'quse_list':quse_list
    }
    template=loader.get_template("subject1.html")
    res=template.render(context,request)
    return HttpResponse(res)

@csrf_exempt # include  this
def result1(request):
    if request.method=='POST':
        subject='DBMS'
        correct=0
        total=4
        for i in range(1,7,1): # traverse total number of questions
            if ('id'+str(i)) in request.POST.keys():  
                q_id=request.POST['id'+str(i)]
                ans=request.POST['option'+str(i)]
                ques=Test_paper_subject1.objects.filter(q_id=q_id)
                if(len(ques.filter(ans=ans))):
                    correct=correct+1
        wrong=total-correct
        percentage=(correct/total)*100
        username=request.session.get('username')
        history=Test_history()
        history.subject=subject
        history.username=User.objects.get(username=username)
        history.total=total
        history.correct=correct
        history.wrong=wrong
        history.percentage=percentage
        history.save()
        context={
            'total':total,
            'correct':correct,
            'wrong':wrong,
            'percentage':percentage
        }
        template=loader.get_template("result1.html")
        res=template.render(context,request)
        return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    
def subject2(request):
    ques=Test_paper_subject2.objects.all()
    quse_list=list(ques)
    random.shuffle(quse_list)
    quse_list=quse_list[:4:1] ###### total questions can be customized
    context={
        'quse_list':quse_list
    }
    template=loader.get_template("subject2.html")
    res=template.render(context,request)
    return HttpResponse(res)

@csrf_exempt # include  this
def result2(request):
    if request.method=='POST':
        subject='OS'
        correct=0
        total=4
        for i in range(1,7,1): # traverse total number of questions
            if ('id'+str(i)) in request.POST.keys():  
                q_id=request.POST['id'+str(i)]
                ans=request.POST['option'+str(i)]
                ques=Test_paper_subject2.objects.filter(q_id=q_id)
                if(len(ques.filter(ans=ans))):
                    correct=correct+1
        wrong=total-correct
        percentage=(correct/total)*100
        username=request.session.get('username')
        history=Test_history()
        history.username=User.objects.get(username=username)
        history.subject=subject
        history.total=total
        history.correct=correct
        history.wrong=wrong
        history.percentage=percentage
        history.save()
        context={
            'total':total,
            'correct':correct,
            'wrong':wrong,
            'percentage':percentage
        }
        template=loader.get_template("result2.html")
        res=template.render(context,request)
        return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    
def subject3(request):
    ques=Test_paper_subject3.objects.all()
    quse_list=list(ques)
    random.shuffle(quse_list)
    quse_list=quse_list[:4:1] ###### total questions can be customized
    context={
        'quse_list':quse_list
    }
    template=loader.get_template("subject3.html")
    res=template.render(context,request)
    return HttpResponse(res)

@csrf_exempt # include  this
def result3(request):
    if request.method=='POST':
        subject='CN'
        correct=0
        total=4 #total number of questions displayed on subject3.html
        for i in range(1,7,1): # traverse total number of questions
            if ('id'+str(i)) in request.POST.keys():  
                q_id=request.POST['id'+str(i)]
                ans=request.POST['option'+str(i)]
                ques=Test_paper_subject3.objects.filter(q_id=q_id)
                if(len(ques.filter(ans=ans))):
                    correct=correct+1
        wrong=total-correct
        percentage=(correct/total)*100
        username=request.session.get('username')
        history=Test_history()
        history.username=User.objects.get(username=username)
        history.subject=subject
        history.total=total

online_test/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project</title>
</head>
<style>
  body{
    background-image: linear-gradient(to bottom, #4E65FF,   #92EFFD);
  }
      #text .card {
        background-image: linear-gradient(to bottom, #8e9eab,   #eef2f3);
        border: 1px solid #0b0b0b;
        border-radius: 8px;
        padding: 20px;
        margin: 10px;
        width: 600px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s;
        animation: slideInFromBottom 1s ease-out, fadeInCard 1s ease-out; /* Adding animation */
      }

      .card:hover {
        transform: scale(1.05);
      }

      /* Animation for card */
      @keyframes slideInFromBottom {
        0% {
          transform: translateY(100%);
          opacity: 0;
        }
        100% {
          transform: translateY(0);
          opacity: 1;
        }
      }

      @keyframes fadeInCard {
        0% {
          opacity: 0;
        }
        100% {
          opacity: 1;
        }
      }

      /* Animation for navbar */
      @keyframes slideInFromLeft {
        0% {
          transform: translateX(-100%);
        }
        100% {
          transform: translateX(0);
        }
      }

      .navbar {
        animation: slideInFromLeft 1s ease-out;
      }

      /* Animation for text */
      @keyframes fadeIn {
        0% {
          opacity: 0;
        }
        100% {
          opacity: 1;
        }
      }

      #text {
        animation: fadeIn 1s ease-out;
      }
      
 .container-fluid{
    background-color: rgba(204, 240, 234, 0.831);
    display:flex;
    justify-content: space-evenly;
}

#container{
    display:flex;
}

#text{
    margin-top:2.5rem;
    margin-left:10rem;
}

.social_media i:hover{
    opacity:1;
    transform: scale(1.3);
}

*{
    margin:0;
    padding:0;
    font-family: 'Poppins', sans-serif;

}
.navbar-brand {
    font-family: 'Times New Roman', Times, serif; /* Use Poppins font */
    font-size: 40px;
    font-weight: bold; /* Make the font bold */
  }

  .navbar-nav .nav-link {
    font-family: 'Poppins', sans-serif; /* Use Poppins font */
    font-weight: bold; /* Make the font bold */
  }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="style.css">
<link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="font-size:40px;">Online Testing System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:aboutUs' %}">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:profile' %}">Update Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:test_history' %}">Test History</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Subject's
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'user:subject1' %}">DBMS</a></li>
              <li><a class="dropdown-item" href="{% url 'user:subject2' %}">OS</a></li>
              <li><a class="dropdown-item" href="{% url 'user:subject3' %}">CN</a></li>
              <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div id="container">
    <div id="text">
      <h2>Test With Ease - Go Online</h2>
      <p>Profile Info :</p>
      <div class="card">
        {% for ele in user_data %}
          <h2>Name :{{ele.name}}</h2>
        {% endfor %}
        {% for ele in profile_data %}
          <h2>Father's Name :{{ele.fathers_name}}</h2>
          <h2>Mother's Name :{{ele.mothers_name}}</h2>
          <h2>Phone :{{ele.phone}}</h2>
          <h2>Email :{{ele.email}}</h2>
          <h2>Address :{{ele.address}}</h2>
        {% endfor %}
      </div>
    </div>
  </div>
</body>
</html>

online_test/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
      }
    
      .login-container {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 50px rgba(0, 0, 0, 0.1);
        width: 400px;
        font-size: larger;
      }

      h1 {
        text-align: center;
        color: #333;
      }

      label {
        display: block;
        margin: 10px 0 5px;
        color: #555;
      }

      input {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
      }

      button {
        background-color: #4caf50;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
        font-size: medium;
      }

      button:hover {
        background-color: #45a049;
      }
    </style>
  </head>
  <body>
    <div class="login-container">
      <h1>Login</h1>
      {{msg}}
      <form method="post" action="{% url 'user:login' %}">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required />

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required />

        <button type="submit">Login</button>
      </form>
      <p>Don't have an account? <a href="{% url 'user:signup'%}">Sign up</a></p>
    </div>
  </body>
</html>

online_test/templates/result1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column; /* Stack elements vertically */
            height: 100vh;
            margin: 0;
            background-image: linear-gradient(to bottom, #09203F, #537895); /* Linear gradient background */
            font-family: 'Poppins', sans-serif; /* Apply Google Font */
        }

        .heading {
            margin-bottom: 20px;
            text-align: center;
        }

        .heading h1 {
            font-size: 36px; /* Increase font size */
            color: #fff; /* Change text color */
            text-shadow: 4px 4px 2px rgba(0, 0, 0, 0.5);
        }

        .card, .card1 {
          background-image: linear-gradient(to bottom, #FFECD2,  #FCB69F);
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 10px;
            width: 600px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s, box-shadow 0.3s;
            animation: fadeIn 1s ease-out;
        }

        .card h1, .card1 b {
            font-size: 24px; /* Specify font size */
        }

        .card:hover, .card1:hover {
            transform: scale(1.05);
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-50px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Animation for hover effect */
        .card:hover .card1 {
            transform: scale(1.1);
            transition: transform 0.3s;
        }

        .card1:hover {
            transform: scale(1.1);
            transition: transform 0.3s;
        }
    </style>
</head>
<body>
  <div class="heading">
    <h1>This is result page</h1>
  </div>
    <div class="card">
        <h1>Total number of questions={{total}}</h1>
        <h1>Total number of correct attempt={{correct}}</h1>
        <h1>Total number of wrong attempt={{wrong}}</h1>
        <h1>Result percentage={{percentage}}</h1>
    </div>
    <div class="card1">
        <b><a href="{% url 'user:homepage' %}" style="text-decoration: none; color: #333;">Go back to home page</a></b><br><br>
        <b><a href="{% url 'user:logout' %}" style="text-decoration: none; color: #333;">Logout</a></b>
    </div>
</body>
</html>

online_test/templates/result2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column; /* Stack elements vertically */
            height: 100vh;
            margin: 0;
            background-image: linear-gradient(to bottom, #09203F, #537895); /* Linear gradient background */
            font-family: 'Poppins', sans-serif; /* Apply Google Font */
        }

        .heading {
            margin-bottom: 20px;
            text-align: center;
        }

        .heading h1 {
            font-size: 36px; /* Increase font size */
            color: #fff; /* Change text color */
            text-shadow: 4px 4px 2px rgba(0, 0, 0, 0.5);
        }

        .card, .card1 {
          background-image: linear-gradient(to bottom, #FFECD2,  #FCB69F);
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 10px;
            width: 600px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s, box-shadow 0.3s;
            animation: fadeIn 1s ease-out;
        }

        .card h1, .card1 b {
            font-size: 24px; /* Specify font size */
        }

        .card:hover, .card1:hover {
            transform: scale(1.05);
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-50px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Animation for hover effect */
        .card:hover .card1 {
            transform: scale(1.1);
            transition: transform 0.3s;
        }

        .card1:hover {
            transform: scale(1.1);
            transition: transform 0.3s;
        }
    </style>
</head>
<body>
  <div class="heading">
    <h1>This is result page</h1>
  </div>
    <div class="card">
        <h1>Total number of questions={{total}}</h1>
        <h1>Total number of correct attempt={{correct}}</h1>
        <h1>Total number of wrong attempt={{wrong}}</h1>
        <h1>Result percentage={{percentage}}</h1>
    </div>
    <div class="card1">
        <b><a href="{% url 'user:homepage' %}" style="text-decoration: none; color: #333;">Go back to home page</a></b><br><br>
        <b><a href="{% url 'user:logout' %}" style="text-decoration: none; color: #333;">Logout</a></b>
    </div>
</body>
</html>

online_test/templates/result3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column; /* Stack elements vertically */
            height: 100vh;
            margin: 0;
            background-image: linear-gradient(to bottom, #09203F, #537895); /* Linear gradient background */
            font-family: 'Poppins', sans-serif; /* Apply Google Font */
        }

        .heading {
            margin-bottom: 20px;
            text-align: center;
        }

        .heading h1 {
            font-size: 36px; /* Increase font size */
            color: #fff; /* Change text color */
            text-shadow: 4px 4px 2px rgba(0, 0, 0, 0.5);
        }

        .card, .card1 {
          background-image: linear-gradient(to bottom, #FFECD2,  #FCB69F);
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 10px;
            width: 600px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s, box-shadow 0.3s;
            animation: fadeIn 1s ease-out;
        }

        .card h1, .card1 b {
            font-size: 24px; /* Specify font size */
        }

        .card:hover, .card1:hover {
            transform: scale(1.05);
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-50px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Animation for hover effect */
        .card:hover .card1 {
            transform: scale(1.1);
            transition: transform 0.3s;
        }

        .card1:hover {
            transform: scale(1.1);
            transition: transform 0.3s;
        }
    </style>
</head>
<body>
  <div class="heading">
    <h1>This is result page</h1>
  </div>
    <div class="card">
        <h1>Total number of questions={{total}}</h1>
        <h1>Total number of correct attempt={{correct}}</h1>
        <h1>Total number of wrong attempt={{wrong}}</h1>
        <h1>Result percentage={{percentage}}</h1>
    </div>
    <div class="card1">
        <b><a href="{% url 'user:homepage' %}" style="text-decoration: none; color: #333;">Go back to home page</a></b><br><br>
        <b><a href="{% url 'user:logout' %}" style="text-decoration: none; color: #333;">Logout</a></b>
    </div>
</body>
</html>

online_test/templates/store_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>user created successfully!!!!!</h1>
    <a href="{% url 'user:login' %}">click here to login</a>
    <a href="{% url 'user:welcome' %}">click here for homepage</a>
</body>
</html>